#! /bin/zsh

cd ~/Rosi

# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi Helpers -e zip,length,Dict,eqStr,expectTrue1,expectTrue2,expectFalse


# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi TableAPI


# constructors
# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi TestTableAPI \
# -e crossExample,leftJoinExample1,leftJoinExample1Expected,leftJoinExample2,leftJoinExample2Expected

# properties

cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi TestTableAPI \
-e nrowsExample,tfilterExample,tfilterExampleExpected

# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi

# Access Subcomponents
# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi TestTableAPI \
# -e selectColumnsStudents,selectColumnsAltStudents,selectColumnsStudentsExpected,dropColumnStudents,dropColumn2Students,dropColumnStudentsExpected,dropColumnsStudents,dropColumns2Students,dropColumnsStudentsExpected

# ordering


# utilities
# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi TestTableAPI \
# -e selectStudents,selectStudentsExpected

# ExampleTables
# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi ExampleTables -e students

# Helpers
cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi TestHelpers \
-e emptyDict,dict,get1,get2,get3,getMissing,getEmpty,set1,set2,set3,setMissing,setEmpty,inc1,inc2,inc3,incMissing,incEmpty,nothingRecordExample,nothingRecordExampleExpected,eqPExample,nothingRecordPrj

# aggregate
# cabal run Rosi -- --print-instantiations -i rolib -i ../B2T2-Rosi/Media/Rosi TestTableAPI \
# -e countFavoriteNumber,falseVal,studentsFavoriteColorsAsTable,studentsFavoriteColorsAsTableExpected

# test printing

# cabal run Rosi -- -i rolib -i ../B2T2-Rosi/Media/Rosi TestTableApi \
# -e studentsWithDupeColors,studentsFavoriteColorsAsDict,getDictSuccess,getDictFailure,studentsFavoriteColorsAsTable
#  -e emptyDict,dict,get1,get2,get3,getMissing,getEmpty,set1,set2,set3,setMissing,setEmpty,inc1,inc2,inc3,incMissing,incEmpty
# -e concreteVariant,concreteVariantInList,labeledWithVar,labeledWithVarViaCon,labeledWithShorthand,labeledWithShorthandVar

