#! /bin/zsh

cd ~/Rosi

cabal run Rosi -- -i rolib -i examples -i ../B2T2-Rosi/Media/Rosi Helpers -e zip


cabal run Rosi -- -i rolib -i examples -i ../B2T2-Rosi/Media/Rosi TableAPI -e Table,emptyTable,addRows,addColumn,buildColumn

cabal run Rosi -- -i rolib -i examples -i ../B2T2-Rosi/Media/Rosi ExampleTables -e students
